/**:
  controller_manager:
    ros__parameters:
      update_rate: 100

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

  diff_drive_controller:
    ros__parameters:
      use_sim_time: true

      left_wheel_names: ["joint_left_wheel"]
      right_wheel_names: ["joint_right_wheel"]

      command_interfaces: ["velocity"]
      state_interfaces: ["velocity", "position"]

      wheel_separation: 0.10
      wheel_radius: 0.035

      use_stamped_vel: false

      base_frame_id: base_link

      linear.x.has_velocity_limits: true
      linear.x.max_velocity: 1.0
      linear.x.has_acceleration_limits: true
      linear.x.max_acceleration: 1.0

      angular.z.has_velocity_limits: true
      angular.z.max_velocity: 2.0
      angular.z.has_acceleration_limits: true
      angular.z.max_acceleration: 2.0